import time

senha1= 'da'.lower()
autenticacao1 = 1

def leiaSenha(msg):
	ok = False
	while True:
		senha = str(input(msg))
		if senha == senha1 :
			ok = True
		else:
			print('\033[0;31mERRO! Digite a senha válida\033[m')
		if ok:
			break
	return senha

def leiaAutenticacao(msg):
	ok = False
	while True:
		autenticacao = int(input(msg))
		if autenticacao == autenticacao1 :
			ok = True
		else:
			print('\033[0;31mERRO! Digite a autenticação válida\033[m')
		if ok:
			break
	return autenticacao

def leiaOpcao(msg):
	ok = False
	while True:
		opcao = int(input(msg))
		if opcao == 1 or opcao == 2 :
			ok = True
		else:
			print('\033[0;31mERRO! Digite uma opção válida\033[m')
		if ok:
			break
	return opcao

def leiaCriptografia(msg):
	ok = False
	while True:
		criptografar = str(input(msg))
		if criptografar == 'sim' or  criptografar == 'nao' or criptografar == 'não':
			ok = True
		else:
			print('\033[0;31mERRO! Digite uma opção válida\033[m')
		if ok:
			break
	return criptografar

def leiaNcarteira(msg):
	ok = False
	while True:
		ncarteira = int(input(msg))
		if ncarteira == 1 or ncarteira == 2 or ncarteira == 3 or ncarteira == 4 or ncarteira == 5 or ncarteira == 6 :
			ok = True
		else:
			print('\033[0;31mERRO! Digite uma opção válida\033[m')
		if ok:
			break
	return ncarteira

print('')
print('Access Matheus')
print('')
senha = leiaSenha('Digite sua senha: ')
print('')
autenticacao = leiaAutenticacao('Digite sua autenticação: ')
print('')
print('Bem vindo Matheus')
print('')

#senha = str(input('Digite sua senha: ')).strip().lower().upper()
#if senha == senha1:
#	print(' ')

#else:
#	while senha != senha1:
#		senha = str(input('Senha errada, tente novamente: ')).strip().lower().upper()
#		print(' ')

#autenticacao = int(input('Digite a autenticação: '))
#if autenticacao == autenticacao1:
#	print(' ')
#	print('Bem vindo, Matheus')
#
#else:
#	while autenticacao != autenticacao1:
#		autenticacao = int(input('Autenticação errada, tente novamente: '))
#		print(' ')
#	print('Bem vindo, Matheus')

# print(' ')
# print('------------------')
# print('[1] Login')
# print('[2] Locate')
# print('------------------')
# print(' ')

#opcao = int(input('Digite o número da opção que deseja: '))

opcao = leiaOpcao('Digite o número da opção que deseja: ')

if opcao == 1:
	print(' ')
	print('''Adaptador Ethernet Ethernet:

   Sufixo DNS específico de conexão. . . . . . :
   Endereço IPv6 . . . . . . . . . . : 2804:7f4:c780:3628:ada2:7b8:6f2:8c25
   Endereço IPv6 Temporário. . . . . . . . : 2804:7f4:c780:3628:754a:1e0a:1120:728f
   Endereço IPv6 de link local . . . . . . . . : fe80::ada2:7b8:6f2:8c25%17
   Endereço IPv4. . . . . . . .  . . . . . . . : 192.168.15.77
   Máscara de Sub-rede . . . . . . . . . . . . : 255.255.255.0
   Gateway Padrão. . . . . . . . . . . . . . . : fe80::dac6:78ff:fecf:7320%17
                                                 192.168.15.1

Adaptador de Rede sem Fio Wi-Fi:

   Estado da mídia. . . . . . . . . . . . . .  : mídia desconectada
   Sufixo DNS específico de conexão. . . . . . :

Adaptador de Rede sem Fio Conexão Local* 9:

   Estado da mídia. . . . . . . . . . . . . .  : mídia desconectada
   Sufixo DNS específico de conexão. . . . . . :

Adaptador de Rede sem Fio Conexão Local* 10:

   Estado da mídia. . . . . . . . . . . . . .  : mídia desconectada
   Sufixo DNS específico de conexão. . . . . . :''')
	print(' ')
	print(' ')
	print(' ')
	print('A rede não possui segurança a nível de criptografia de ponta a ponta, ')
	print(' ')

	criptografar = leiaCriptografia('Deseja criptografar a conexão do programa, assim criando um a canal seguro? ')

	if criptografar == 'sim'.upper().lower():
			print('')
			print(' ')
			print('''JDxK4ZlvptmPYmK3LmYd3QoSFXpHI4FBYOQJ2GBG7LrBz4lOODYq291W7lSnraA-dXOO
			u1JjP8Lsusb5jP6NyYkUFDlCBCs4Rixcx2IKhOB88opiTEBQHyTfNf2XDjDORLlaFjOlLaxr2nxnQ
			juydnq0zRsmF0m83JqQbNkcUmPTwzuVxVQ5MXnHoyjtRlxk0eR3OmKwtmG_Re5q9BYPpZQ7mepTZp
			DJ6fkJMfqYdtS_n_RH43E3Bw_LM3K90qOR''')
			print(' ')
			print(' ')
			# voltar para o menu

	if criptografar =='não'.upper().lower():
			print('')
			print("Não foi possível fazer o login")
			#voltar para o menu

	if criptografar == 'nao'.upper().lower():
		print('')
		print("Não foi possível fazer o login")
		# voltar para o menu

	#else:
			#while criptografar != 'sim' and criptografar !='não' and criptografar !='nao':
			#	criptografar = str(input('Opção inválida, por favor digite sim ou não: '))


			#	if criptografar == 'sim'.upper().lower():
			#		print("Mesagens de criptografia...")
				# voltar para o menu

				#if criptografar == 'não'.upper().lower():
				#	print("Não foi possível fazer o login")
				# voltar para o menu

			#	if criptografar == 'nao'.upper().lower():
				#	print("Não foi possível fazer o login")
			# voltar para o menu

if opcao == 2:
	print('''	Carteiras dísponíveis:
	Carteira R1
	Carteira R2
	Carteira R3
	Carteira R4
	Carteira I1
	Carteira FTX''')
	print(' ')
	opcao1 = leiaCriptografia('Deseja inspecionar o circuito interno? ')
	if opcao1 == 'sim'.upper().lower():

		print('')
		ncarteira = leiaNcarteira('Digite o número da carteira: ')
		print('')

		saldo1 = float(1.066)
		saldo2 = float(2.87)
		saldo3 = float(0.3)
		saldo4 = float(40.33)
		saldo5 = float(6.78)
		saldo6 = float(1.85)

		if ncarteira == 1:
					print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo1))
					print('')
					transfer= str(input('Deseja movimentar o circuito interno? '))
					print('')
					if transfer == 'sim'.upper().lower():
						print('')
						valor = float(input('Qualifique a tranferencia: '))
						print('')
						destino = leiaNcarteira('Qual a carteira de destino? (digite o número da carteira): ')
						taxa =  float(0.041)
						print('')
						confirmar = leiaCriptografia("O valor de taxa de gás é {}, digite sim, para confirmar a transação: ".format(taxa))
						if confirmar == 'sim'.upper().lower().strip():
							if destino ==1 :
								saldo1=saldo1+valor-taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R1 é {}'.format(saldo1))
							if destino == 2:
									saldo2=saldo2+valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
							if destino == 3:
									saldo3 = saldo3 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
							if destino == 4:
										saldo4 = saldo4 + valor-taxa
										print('Transação 10% conlcuída')
										time.sleep(18)
										print('Transação 20% conlcuída')
										time.sleep(18)
										print('Transação 30% conlcuída')
										time.sleep(18)
										print('Transação 40% conlcuída')
										time.sleep(18)
										print('Transação 50% conlcuída')
										time.sleep(18)
										print('Transação 60% conlcuída')
										time.sleep(18)
										print('Transação 70% conlcuída')
										time.sleep(18)
										print('Transação 80% conlcuída')
										time.sleep(18)
										print('Transação 90% conlcuída')
										time.sleep(18)
										print('Transação 99% conlcuída')
										time.sleep(18)
										print('Transação completamente conlcuída')
										print('O saldo da carteira R4 é {}'.format(saldo4))
							if destino == 5:
									saldo5 = saldo5 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
							if destino == 6:
									saldo6 = saldo6 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
							# else:
							# 		while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
							# 			destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
							# 		if destino == 1:
							# 				saldo1 = saldo1 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R1 é {}'.format(saldo1))
							# 		if destino == 2:
							# 				saldo2 = saldo2 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R2 é {}'.format(saldo2))
									# if destino == 3:
									# 		saldo3 = saldo3 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R3 é {}'.format(saldo3))
									# if destino == 4:
									# 		saldo4 = saldo4 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R4 é {}'.format(saldo4))
									# if destino == 5:
									# 		saldo5 = saldo5 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R5 é {}'.format(saldo5))
									# if destino == 6:
									# 		saldo6 = saldo6 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R6 é {}'.format(saldo6))
					else:
						print('Transação cancelada')
		#else:
			#print('')
		if ncarteira == 2:
			print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo2))
			print('')
			transfer = str(input('Deseja transferir o saldo? '))
			print('')
			if transfer == 'sim'.upper().lower():
				print('')
				valor = float(input('Qual valor deseja tranferir? '))
				print('')
				destino = leiaNcarteira('Qual a carteira de destino? (digite o número da carteira): ')
				taxa = float(0.041)
				print('')
				confirmar = leiaCriptografia("O valor da taxa é {}, digite sim, para confirmar a transação: ".format(taxa))
				if confirmar == 'sim'.upper().lower().strip():
					if destino == 1:
						saldo1 = saldo1 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R1 é {}'.format(saldo1))
					if destino == 2:
						saldo2 = saldo2 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R2 é {}'.format(saldo2))
					if destino == 3:
						saldo3 = saldo3 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R3 é {}'.format(saldo3))
					if destino == 4:
						saldo4 = saldo4 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R4 é {}'.format(saldo4))
					if destino == 5:
						saldo5 = saldo5 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R5 é {}'.format(saldo5))
					if destino == 6:
						saldo6 = saldo6 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R6 é {}'.format(saldo6))
			# else:
			# 		while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
			# 			destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
			# 		if destino == 1:
			# 				saldo1 = saldo1 + valor - taxa
			# 				print('Transação 10% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 20% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 30% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 40% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 50% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 60% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 70% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 80% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 90% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 99% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação completamente conlcuída')
			# 				print('O saldo da carteira R1 é {}'.format(saldo1))
			# 		if destino == 2:
			# 				saldo2 = saldo2 + valor - taxa
			# 				print('Transação 10% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 20% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 30% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 40% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 50% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 60% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 70% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 80% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 90% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação 99% conlcuída')
			# 				time.sleep(18)
			# 				print('Transação completamente conlcuída')
			# 				print('O saldo da carteira R2 é {}'.format(saldo2))
			# if destino == 3:
			# 		saldo3 = saldo3 + valor - taxa
			# 		print('Transação 10% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 20% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 30% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 40% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 50% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 60% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 70% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 80% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 90% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 99% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação completamente conlcuída')
			# 		print('O saldo da carteira R3 é {}'.format(saldo3))
			# if destino == 4:
			# 		saldo4 = saldo4 + valor - taxa
			# 		print('Transação 10% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 20% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 30% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 40% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 50% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 60% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 70% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 80% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 90% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 99% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação completamente conlcuída')
			# 		print('O saldo da carteira R4 é {}'.format(saldo4))
			# if destino == 5:
			# 		saldo5 = saldo5 + valor - taxa
			# 		print('Transação 10% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 20% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 30% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 40% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 50% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 60% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 70% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 80% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 90% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 99% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação completamente conlcuída')
			# 		print('O saldo da carteira R5 é {}'.format(saldo5))
			# if destino == 6:
			# 		saldo6 = saldo6 + valor - taxa
			# 		print('Transação 10% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 20% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 30% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 40% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 50% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 60% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 70% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 80% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 90% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação 99% conlcuída')
			# 		time.sleep(18)
			# 		print('Transação completamente conlcuída')
			# 		print('O saldo da carteira R6 é {}'.format(saldo6))
			else:
				print('Transação cancelada')
# else:
# print('')

		if ncarteira == 3:
					print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo3))
					print('')
					transfer= str(input('Deseja transferir o saldo? '))
					print('')
					if transfer == 'sim'.upper().lower():
						print('')
						valor = float(input('Qual valor deseja tranferir? '))
						print('')
						destino = leiaNcarteira('Qual a carteira de destino? (digite o número da carteira): ')
						taxa =  float(0.041)
						print('')
						confirmar = leiaCriptografia("O valor da taxa é {}, digite sim, para confirmar a transação: ".format(taxa))
						if confirmar == 'sim'.upper().lower().strip():
							if destino ==1 :
								saldo1=saldo1+valor-taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R1 é {}'.format(saldo1))
							if destino == 2:
									saldo2=saldo2+valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
							if destino == 3:
									saldo3 = saldo3 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
							if destino == 4:
										saldo4 = saldo4 + valor-taxa
										print('Transação 10% conlcuída')
										time.sleep(18)
										print('Transação 20% conlcuída')
										time.sleep(18)
										print('Transação 30% conlcuída')
										time.sleep(18)
										print('Transação 40% conlcuída')
										time.sleep(18)
										print('Transação 50% conlcuída')
										time.sleep(18)
										print('Transação 60% conlcuída')
										time.sleep(18)
										print('Transação 70% conlcuída')
										time.sleep(18)
										print('Transação 80% conlcuída')
										time.sleep(18)
										print('Transação 90% conlcuída')
										time.sleep(18)
										print('Transação 99% conlcuída')
										time.sleep(18)
										print('Transação completamente conlcuída')
										print('O saldo da carteira R4 é {}'.format(saldo4))
							if destino == 5:
									saldo5 = saldo5 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
							if destino == 6:
									saldo6 = saldo6 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
							# else:
							# 		while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
							# 			destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
							# 		if destino == 1:
							# 				saldo1 = saldo1 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R1 é {}'.format(saldo1))
							# 		if destino == 2:
							# 				saldo2 = saldo2 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R2 é {}'.format(saldo2))
									# if destino == 3:
									# 		saldo3 = saldo3 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R3 é {}'.format(saldo3))
									# if destino == 4:
									# 		saldo4 = saldo4 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R4 é {}'.format(saldo4))
									# if destino == 5:
									# 		saldo5 = saldo5 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R5 é {}'.format(saldo5))
									# if destino == 6:
									# 		saldo6 = saldo6 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R6 é {}'.format(saldo6))
					else:
						print('Transação cancelada')
		#else:
			#print('')

		if ncarteira == 4:
					print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo4))
					print('')
					transfer= str(input('Deseja transferir o saldo? '))
					print('')
					if transfer == 'sim'.upper().lower():
						print('')
						valor = float(input('Qual valor deseja tranferir? '))
						print('')
						destino = leiaNcarteira('Qual a carteira de destino? (digite o número da carteira): ')
						taxa =  float(0.041)
						print('')
						confirmar = leiaCriptografia("O valor da taxa é {}, digite sim, para confirmar a transação: ".format(taxa))
						if confirmar == 'sim'.upper().lower().strip():
							if destino ==1 :
								saldo1=saldo1+valor-taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R1 é {}'.format(saldo1))
							if destino == 2:
									saldo2=saldo2+valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
							if destino == 3:
									saldo3 = saldo3 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
							if destino == 4:
										saldo4 = saldo4 + valor-taxa
										print('Transação 10% conlcuída')
										time.sleep(18)
										print('Transação 20% conlcuída')
										time.sleep(18)
										print('Transação 30% conlcuída')
										time.sleep(18)
										print('Transação 40% conlcuída')
										time.sleep(18)
										print('Transação 50% conlcuída')
										time.sleep(18)
										print('Transação 60% conlcuída')
										time.sleep(18)
										print('Transação 70% conlcuída')
										time.sleep(18)
										print('Transação 80% conlcuída')
										time.sleep(18)
										print('Transação 90% conlcuída')
										time.sleep(18)
										print('Transação 99% conlcuída')
										time.sleep(18)
										print('Transação completamente conlcuída')
										print('O saldo da carteira R4 é {}'.format(saldo4))
							if destino == 5:
									saldo5 = saldo5 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
							if destino == 6:
									saldo6 = saldo6 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
							# else:
							# 		while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
							# 			destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
							# 		if destino == 1:
							# 				saldo1 = saldo1 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R1 é {}'.format(saldo1))
							# 		if destino == 2:
							# 				saldo2 = saldo2 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R2 é {}'.format(saldo2))
									# if destino == 3:
									# 		saldo3 = saldo3 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R3 é {}'.format(saldo3))
									# if destino == 4:
									# 		saldo4 = saldo4 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R4 é {}'.format(saldo4))
									# if destino == 5:
									# 		saldo5 = saldo5 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R5 é {}'.format(saldo5))
									# if destino == 6:
									# 		saldo6 = saldo6 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R6 é {}'.format(saldo6))
					else:
						print('Transação cancelada')
		#else:
			#print('')
		if ncarteira == 5:
			print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo5))
			print('')
			transfer = str(input('Deseja transferir o saldo? '))
			print('')
			if transfer == 'sim'.upper().lower():
				print('')
				valor = float(input('Qual valor deseja tranferir? '))
				print('')
				destino = leiaNcarteira('Qual a carteira de destino? (digite o número da carteira): ')
				taxa = float(0.041)
				print('')
				confirmar = leiaCriptografia("O valor da taxa é {}, digite sim, para confirmar a transação: ".format(taxa))
				if confirmar == 'sim'.upper().lower().strip():
					if destino == 1:
						saldo1 = saldo1 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R1 é {}'.format(saldo1))
					if destino == 2:
						saldo2 = saldo2 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R2 é {}'.format(saldo2))
					if destino == 3:
						saldo3 = saldo3 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R3 é {}'.format(saldo3))
					if destino == 4:
						saldo4 = saldo4 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R4 é {}'.format(saldo4))
					if destino == 5:
						saldo5 = saldo5 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R5 é {}'.format(saldo5))
					if destino == 6:
						saldo6 = saldo6 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R6 é {}'.format(saldo6))
		# else:
		# 		while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
		# 			destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
		# 		if destino == 1:
		# 				saldo1 = saldo1 + valor - taxa
		# 				print('Transação 10% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 20% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 30% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 40% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 50% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 60% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 70% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 80% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 90% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 99% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação completamente conlcuída')
		# 				print('O saldo da carteira R1 é {}'.format(saldo1))
		# 		if destino == 2:
		# 				saldo2 = saldo2 + valor - taxa
		# 				print('Transação 10% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 20% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 30% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 40% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 50% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 60% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 70% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 80% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 90% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação 99% conlcuída')
		# 				time.sleep(18)
		# 				print('Transação completamente conlcuída')
		# 				print('O saldo da carteira R2 é {}'.format(saldo2))
		# if destino == 3:
		# 		saldo3 = saldo3 + valor - taxa
		# 		print('Transação 10% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 20% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 30% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 40% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 50% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 60% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 70% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 80% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 90% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 99% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação completamente conlcuída')
		# 		print('O saldo da carteira R3 é {}'.format(saldo3))
		# if destino == 4:
		# 		saldo4 = saldo4 + valor - taxa
		# 		print('Transação 10% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 20% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 30% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 40% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 50% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 60% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 70% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 80% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 90% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 99% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação completamente conlcuída')
		# 		print('O saldo da carteira R4 é {}'.format(saldo4))
		# if destino == 5:
		# 		saldo5 = saldo5 + valor - taxa
		# 		print('Transação 10% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 20% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 30% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 40% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 50% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 60% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 70% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 80% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 90% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 99% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação completamente conlcuída')
		# 		print('O saldo da carteira R5 é {}'.format(saldo5))
		# if destino == 6:
		# 		saldo6 = saldo6 + valor - taxa
		# 		print('Transação 10% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 20% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 30% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 40% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 50% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 60% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 70% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 80% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 90% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação 99% conlcuída')
		# 		time.sleep(18)
		# 		print('Transação completamente conlcuída')
		# 		print('O saldo da carteira R6 é {}'.format(saldo6))
			else:
				print('Transação cancelada')
# else:
# print('')
		if ncarteira == 6:
					print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo6))
					print('')
					transfer= str(input('Deseja transferir o saldo? '))
					print('')
					if transfer == 'sim'.upper().lower():
						print('')
						valor = float(input('Qual valor deseja tranferir? '))
						print('')
						destino = leiaNcarteira('Qual a carteira de destino? (digite o número da carteira): ')
						taxa =  float(0.041)
						print('')
						confirmar = leiaCriptografia("O valor da taxa é {}, digite sim, para confirmar a transação: ".format(taxa))
						if confirmar == 'sim'.upper().lower().strip():
							if destino ==1 :
								saldo1=saldo1+valor-taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R1 é {}'.format(saldo1))
							if destino == 2:
									saldo2=saldo2+valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
							if destino == 3:
									saldo3 = saldo3 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
							if destino == 4:
										saldo4 = saldo4 + valor-taxa
										print('Transação 10% conlcuída')
										time.sleep(18)
										print('Transação 20% conlcuída')
										time.sleep(18)
										print('Transação 30% conlcuída')
										time.sleep(18)
										print('Transação 40% conlcuída')
										time.sleep(18)
										print('Transação 50% conlcuída')
										time.sleep(18)
										print('Transação 60% conlcuída')
										time.sleep(18)
										print('Transação 70% conlcuída')
										time.sleep(18)
										print('Transação 80% conlcuída')
										time.sleep(18)
										print('Transação 90% conlcuída')
										time.sleep(18)
										print('Transação 99% conlcuída')
										time.sleep(18)
										print('Transação completamente conlcuída')
										print('O saldo da carteira R4 é {}'.format(saldo4))
							if destino == 5:
									saldo5 = saldo5 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
							if destino == 6:
									saldo6 = saldo6 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
							# else:
							# 		while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
							# 			destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
							# 		if destino == 1:
							# 				saldo1 = saldo1 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R1 é {}'.format(saldo1))
							# 		if destino == 2:
							# 				saldo2 = saldo2 + valor - taxa
							# 				print('Transação 10% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 20% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 30% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 40% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 50% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 60% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 70% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 80% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 90% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação 99% conlcuída')
							# 				time.sleep(18)
							# 				print('Transação completamente conlcuída')
							# 				print('O saldo da carteira R2 é {}'.format(saldo2))
									# if destino == 3:
									# 		saldo3 = saldo3 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R3 é {}'.format(saldo3))
									# if destino == 4:
									# 		saldo4 = saldo4 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R4 é {}'.format(saldo4))
									# if destino == 5:
									# 		saldo5 = saldo5 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R5 é {}'.format(saldo5))
									# if destino == 6:
									# 		saldo6 = saldo6 + valor - taxa
									# 		print('Transação 10% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 20% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 30% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 40% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 50% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 60% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 70% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 80% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 90% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação 99% conlcuída')
									# 		time.sleep(18)
									# 		print('Transação completamente conlcuída')
									# 		print('O saldo da carteira R6 é {}'.format(saldo6))
					else:
						print('Transação cancelada')
		#else:
			#print('')



#if opcao != 1 and opcao !=2:
	#while opcao != 1 and opcao != 2:
	#		opcao = int(input('Opção indisponível, por favor digite a opção 1 ou 2: '))